name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: msa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendras1722/msa@master
